### ISSUE TITLE
Support for Java 17

### ISSUE THREAD

**Issue by ProNibs** [bitnami/bitnami-docker-gradle#1]
### Name and Version

bitnami-docker-gradle

### What is the problem this feature will solve?

Just looking for Java 17 to be added into the base gradle image.

### What is the feature you are proposing to solve the problem?

Java 17 doesn't need to be set as the default JAVA_HOME, would be perfectly fine for this to be a manual setting.

**Comment by marcosbc** [comment]
Hi @ProNibs, unfortunately our release pipeline does not support including multiple versions of Java in an image. In addition, we are currently standarizing either on Java 1.8 or Java 11.

That said, feel free to create a custom base image extending [this one](https://github.com/bitnami/bitnami-docker-gradle/blob/master/7/debian-10/Dockerfile). It should be enough to remove `/opt/bitnami/java` and re-download version 11, using similar steps to the ones listed in the Dockerfile.

**Comment by ProNibs** [comment]
Yeah, was hoping to avoid that and get Java 17 added in by default in advance of Java 11 going EOL and stops active development in a year and security updates in 4 years. 

Do you know how to view what Java versions are available in stacksmith? Would like to mimic as best as I can but wasn't able to find a UI that matches this download link: https://downloads.bitnami.com/files/stacksmith/java-11.0.15-0-linux-amd64-debian-10.tar.gz
